### ISSUE TITLE
Error loading FDS Simulation: "object has no attribute 'particles'"

### ISSUE THREAD

**Issue by TristanHehnen** [FireDynamics/fdsreader#44]
Hi,

I get an error reading FDS simulations with fdsreader version 1.8.4: "AttributeError: 'Simulation' object has no attribute 'particles'" for line 
https://github.com/FireDynamics/fdsreader/blob/856cb3285fdabde062c24a23d1fb4ad52fc6504f/fdsreader/simulation.py#L203

Should it be `self._particles` instead of `self.particles`?

Edit:
Forgot to say that in the simulation there are no particles.

Best,
Tristan

**Comment by JanVogelsang** [comment]
Will have a look

**Comment by JanVogelsang** [comment]
@TristanHehnen Are you sure that there are no particles in the simulation? The fdsreader does definitely find something related to particles, which is why it goes into that line. Could you send me the fds-file?

**Comment by JanVogelsang** [comment]
Probiere es mal mit 1.8.5, Fehler ist gefixt.

**Comment by TristanHehnen** [comment]
Thank you very much!

Unfortunately, it now complains about the next thing...

It's line 112 in `Simulation.py` and it can't find meshes:
"AttributeError: 'Simulation' object has no attribute '_meshes'"

Could this be related to different FDS versions? This file I'm using is for a somewhat older version.

**Comment by JanVogelsang** [comment]
This could very well be caused by an old FDS version, yes, as the SmokeView-File changed a lot during the years. The Fdsreader does only safely support FDS >= 6.7.5.
Either run the simulation again with a newer FDS version or send me the old .smv file, so I can check if I can identify the problem with that version and maybe also (partly) support that version then.

**Comment by TristanHehnen** [comment]
Alright, works now, thank you very much!
